# Generated by Django 4.2.6 on 2023-10-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.everestkitchenpa.com%2Fassets%2Fpages%2FcoldBeverages.html&psig=AOvVaw3bi9bcfBpZUBeMDe4fivPR&ust=1697714665096000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCNjNw4--_4EDFQAAAAAdAAAAABAE', max_length=500),
        ),
    ]
